// Generated by CoffeeScript 1.6.3
(function() {
  var UglifyJS, compile, debug, path;

  UglifyJS = require('uglify-js');

  debug = true;

  compile = function(filePath, cb) {
    var b, browserify, opts, path;
    browserify = require('browserify');
    b = browserify();
    path = require('path');
    filePath = path.resolve(filePath);
    b.add(filePath);
    b.external('jqwidgets');
    b.external('noty');
    b.external('jStorage');
    b.transform('coffeeify');
    b.transform('browserify-shim');
    b.transform('node-lessify');
    b.transform('brfs');
    opts = {
      debug: debug
    };
    return b.bundle(opts, function(err, data) {
      if (debug) {
        return cb(err, data);
      } else {
        if (err) {
          cb(err, null);
          return;
        }
        return cb(null, UglifyJS.minify(data, {
          fromString: true
        }).code);
      }
    });
  };

  if (require.main === module) {
    path = process.argv[2];
    if (!path) {
      throw "Usage: compile.coffee <path>";
    }
    compile(path, function(err, data) {
      if (err) {
        console.log("Error :(\n" + err);
      }
      return console.log(data);
    });
  }

  module.exports = compile;

}).call(this);
